//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiJingWebUI.Services {
    
    
    public partial class Default {
        
        /// <summary>
        /// ArticleMetas1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YiJingWebUI.UserControls.ArticleMetas ArticleMetas1;
        
        /// <summary>
        /// AboutHeader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YiJingWebUI.UserControls.AboutHeader AboutHeader1;
        
        /// <summary>
        /// Footer21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YiJingWebUI.UserControls.Footer2 Footer21;
        
        /// <summary>
        /// SideBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YiJingWebUI.UserControls.SideBar SideBar1;
    }
}
